{{- if .Values.features.gatus }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: gatus-secrets
  namespace: {{ .Values.projectName }}-system
spec:
  path: project-{{ .Values.projectName }}/system/discord 
  vaultRole: project-{{ .Values.projectName }}-system-role
  type: Opaque
  keys:
    - DISCORD_WEBHOOK_URL
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: {{ .Values.projectName }}-system
data:
  config.yaml: |
    alerting:
      discord:
        webhook-url: "${DISCORD_WEBHOOK_URL}"
    kubernetes:
      service-discovery:
        label-selector: "project={{ .Values.projectName }}"
        service-name-template: "[NAME]"
        service-url-template: "http://[NAME].[NAMESPACE].svc.cluster.local:[PORT][PATH]"
    endpoints:
      - name: OpenStack Control Plane
        group: Infrastructure Host
        url: "icmp://192.168.1.210"
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: {{ .Values.projectName }}-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      serviceAccountName: default 
      containers:
        - name: gatus
          image: twinproduction/gatus:v5.7.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          envFrom:
            - secretRef:
                name: gatus-secrets
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: gatus-config
---
apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: {{ .Values.projectName }}-system
spec:
  selector:
    app: gatus
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gatus-route
  namespace: {{ .Values.projectName }}-system
spec:
  parentRefs:
    - name: shared-gateway
      namespace: gateway-infra
  hostnames:
    - "status-{{ .Values.projectName }}.3istor.com"
  rules:
    - backendRefs:
        - name: gatus
          port: 80
{{- end }}