# Gatus-sidecar for auto-discovery: https://github.com/home-operations/gatus-sidecar/tree/main

{{- if .Values.features.gatus }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: gatus-secrets
  namespace: {{ .Values.projectName }}-system
spec:
  path: project-{{ .Values.projectName }}/system/discord 
  vaultRole: project-{{ .Values.projectName }}-system-role
  type: Opaque
  keys:
    - DISCORD_WEBHOOK_URL
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-base-config
  namespace: {{ .Values.projectName }}-system
data:
  gatus-base.yaml: |
    alerting:
      discord:
        webhook-url: "${DISCORD_WEBHOOK_URL}"
    endpoints:
      - name: OpenStack Control Plane
        group: Infrastructure Host
        url: "icmp://192.168.1.210"
        interval: 1m
        conditions:
          - "[CONNECTED] == true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: {{ .Values.projectName }}-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      serviceAccountName: default
      containers:
        - name: gatus
          image: twinproduction/gatus:v5.7.0
          ports:
            - containerPort: 8080
          env:
            - name: GATUS_CONFIG_PATH
              value: "/config" 
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          envFrom:
            - secretRef:
                name: gatus-secrets
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: base-config-volume
              mountPath: /config/gatus-base.yaml
              subPath: gatus-base.yaml

        - name: gatus-sidecar
          image: ghcr.io/home-operations/gatus-sidecar:latest
          args:
            - "--enable-httproute"
            - "--enable-service"
            - "--annotation-enabled"
            - "gatus.3istor.com/{{ .Values.projectName }}-enabled"
            - "--annotation-config"
            - "gatus.3istor.com/{{ .Values.projectName }}-endpoint"
            - "--output"
            - "/config/gatus-sidecar.yaml"
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: config-volume
              mountPath: /config

      volumes:
        - name: config-volume
          emptyDir: {}
        - name: base-config-volume
          configMap:
            name: gatus-base-config
---
apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: {{ .Values.projectName }}-system
spec:
  selector:
    app: gatus
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gatus-route
  namespace: {{ .Values.projectName }}-system
spec:
  parentRefs:
    - name: shared-gateway
      namespace: gateway-infra
  hostnames:
    - "status-{{ .Values.projectName }}.3istor.com"
  rules:
    - backendRefs:
        - name: gatus
          port: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatus-sidecar-{{ .Values.projectName }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes", "gateways"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatus-sidecar-{{ .Values.projectName }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gatus-sidecar-{{ .Values.projectName }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.projectName }}-system
{{- end }}