apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "cnp-project-base.systemNamespace" . }} 
  labels:
    project: {{ .Values.projectName }}
    prod-gateway-access: "true"
    {{- include "cnp-project-base.labels" . | nindent 4 }}
